name: ba-price-predictor
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pandas=1.5.1
  - numpy=1.23.4
  - scikit-learn=1.1.3
  - streamlit=1.45.1
  - plotly=5.11.0
  - matplotlib=3.6.2
  - joblib=1.2.0
  - optuna=4.3.0
  - pip
  - pip:
      - optuna-dashboard==0.18.0
